# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('search_endmpoint', models.CharField(choices=[('Book', 'Book'), ('TV', 'TV'), ('Movie', 'Model'), ('Song', 'Song'), ('General', 'General')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('psid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='db.User'),
        ),
    ]
